const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');

async function run() {
  const configPath = path.join(__dirname, 'src-tauri', 'tauri.conf.json');
  
  // 1. Patch the public key into config.
  // The Tauri signer base64-decodes the pubkey field, then parses the result as UTF-8 minisign text.
  // So the pubkey value must be: base64(full_pub_key_file_text_with_header)
  // The .pub file generated by tauri-cli IS already base64-encoded in this exact format.
  console.log('[build-wrapper] Patching tauri.conf.json with correct public key...');
  let config = JSON.parse(fs.readFileSync(configPath, 'utf8'));

  const pubFilePath = path.join(__dirname, 'final_linux_style.pub');
  // Read the raw .pub file content — it IS already the base64-of-the-full-key-text
  const pubKeyValue = fs.readFileSync(pubFilePath, 'utf8').trim();
  console.log('[build-wrapper] Pubkey value (first 40 chars):', pubKeyValue.substring(0, 40) + '...');
  config.plugins.updater.pubkey = pubKeyValue;
  fs.writeFileSync(configPath, JSON.stringify(config, null, 2));

  // 2. The secret is base64 of the real minisign key text. Decode it.
  const b64Secret = process.env.TAURI_SIGNING_PRIVATE_KEY_B64;
  if (!b64Secret) {
    console.error('[build-wrapper] Error: TAURI_SIGNING_PRIVATE_KEY_B64 is not set');
    process.exit(1);
  }

  const realKeyContent = Buffer.from(b64Secret, 'base64').toString('utf8');
  console.log('[build-wrapper] Decoded private key first line:', realKeyContent.split('\n')[0]);

  // Write to a temp file and point TAURI_SIGNING_PRIVATE_KEY at the file path
  const keyPath = path.join(__dirname, 'src-tauri', '.tmp_signing_key');
  fs.writeFileSync(keyPath, realKeyContent, { encoding: 'utf8' });

  // 3. Run tauri build with the KEY PATH (official Tauri recommended approach)
  const env = { ...process.env, TAURI_SIGNING_PRIVATE_KEY: keyPath };
  
  console.log('[build-wrapper] Starting Tauri build...');
  const child = spawn('npx', ['tauri', 'build'], { 
    env, 
    stdio: 'inherit',
    shell: true 
  });

  child.on('exit', (code) => {
    try { fs.unlinkSync(keyPath); } catch(e) {}
    process.exit(code);
  });
}

run();
